import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, Save, Trash2 } from "lucide-react";
import { useEffect, useState, type FormEvent } from "react";
import { FarmShell, PageIntro } from "@/components/farm-shell";
import { fallbackListings, type Listing } from "@/lib/farm-data";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/products/$id/edit")({
  head: () => ({ meta: [{ title: "Edit listing — Farm to Table" }, { name: "description", content: "Update your produce listing." }, { property: "og:title", content: "Edit listing — Farm to Table" }, { property: "og:description", content: "Update your produce listing." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: EditProduct,
});

function EditProduct() {
  const { id } = Route.useParams();
  const navigate = useNavigate();
  const [listing, setListing] = useState<Listing | null>(fallbackListings.find((item) => item.id === id) ?? null);
  const [notice, setNotice] = useState("");
  useEffect(() => { let active = true; void supabase.from("produce_listings").select("*").eq("id", id).maybeSingle().then(({ data }) => { if (active && data) setListing(data); }); return () => { active = false; }; }, [id]);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!listing) return; const form = new FormData(event.currentTarget); const { error } = await supabase.from("produce_listings").update({ name: String(form.get("name") ?? ""), category: String(form.get("category") ?? "Vegetables"), description: String(form.get("description") ?? ""), price: Number(form.get("price") ?? 0), unit: String(form.get("unit") ?? "kg"), quantity: Number(form.get("quantity") ?? 0), location: String(form.get("location") ?? ""), harvest_date: String(form.get("harvest_date") ?? "") || null, image_url: String(form.get("image_url") ?? "") || null, updated_at: new Date().toISOString() }).eq("id", id); if (error) setNotice(error.message); else { setNotice("Listing saved."); await navigate({ to: "/dashboard" }); } }
  async function remove() { if (!listing) return; const { error } = await supabase.from("produce_listings").delete().eq("id", id); if (error) setNotice(error.message); else await navigate({ to: "/dashboard" }); }
  if (!listing) return <FarmShell><main className="mx-auto max-w-2xl px-5 py-20 text-center"><h1 className="font-display text-5xl">Listing not found.</h1><Link to="/dashboard" className="mt-6 inline-flex rounded-md bg-field px-4 py-3 font-semibold text-paper">Back to dashboard</Link></main></FarmShell>;
  return <FarmShell eyebrow="Edit listing"><PageIntro kicker="Edit harvest listing" title="Keep the details honest." body="Update the quantity, price, or story as the harvest changes." /><main className="mx-auto max-w-3xl px-5 py-10 lg:px-8 lg:py-14"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Back to dashboard</Link><form onSubmit={save} className="mt-7 rounded-lg border border-border bg-card p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Produce name" name="name" defaultValue={listing.name} required /><label className="grid gap-1.5 text-sm font-medium">Category<select name="category" defaultValue={listing.category} className="rounded-md border border-input bg-background px-3 py-3 outline-none focus:border-field"><option>Vegetables</option><option>Fruit</option><option>Leafy greens</option><option>Herbs</option><option>Flowers</option></select></label><Field label="Price" name="price" type="number" defaultValue={listing.price} step="0.01" required /><Field label="Unit" name="unit" defaultValue={listing.unit} required /><Field label="Quantity available" name="quantity" type="number" defaultValue={listing.quantity} step="0.1" required /><Field label="Harvest date" name="harvest_date" type="date" defaultValue={listing.harvest_date ?? ""} /><Field label="Location" name="location" defaultValue={listing.location ?? ""} /><Field label="Image URL" name="image_url" defaultValue={listing.image_url ?? ""} /><label className="grid gap-1.5 text-sm font-medium sm:col-span-2">Description<textarea name="description" defaultValue={listing.description} required className="min-h-32 resize-y rounded-md border border-input bg-background px-3 py-3 outline-none focus:border-field" /></label></div>{notice && <p className="mt-5 text-sm text-field">{notice}</p>}<div className="mt-7 flex flex-wrap justify-between gap-3"><button type="button" onClick={remove} className="inline-flex items-center gap-2 rounded-md border border-destructive/30 px-4 py-3 text-sm font-semibold text-destructive hover:bg-destructive/10"><Trash2 className="size-4" /> Remove listing</button><button type="submit" className="inline-flex items-center gap-2 rounded-md bg-field-deep px-5 py-3 text-sm font-semibold text-paper hover:bg-field"><Save className="size-4" /> Save changes</button></div></form></main></FarmShell>;
}
function Field({ label, name, defaultValue, type = "text", step, required }: { label: string; name: string; defaultValue?: string | number; type?: string; step?: string; required?: boolean }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<input name={name} type={type} step={step} defaultValue={defaultValue} required={required} className="rounded-md border border-input bg-background px-3 py-3 outline-none focus:border-field" /></label>; }