import { createFileRoute, Link, useNavigate } from "@tanstack/react-router";
import { ArrowLeft, ImagePlus, Save } from "lucide-react";
import { useState, type FormEvent } from "react";
import { FarmShell, PageIntro } from "@/components/farm-shell";
import { supabase } from "@/integrations/supabase/client";

export const Route = createFileRoute("/products/new")({
  head: () => ({ meta: [{ title: "Add produce — Farm to Table" }, { name: "description", content: "Create a fresh produce listing for your local marketplace." }, { property: "og:title", content: "Add produce — Farm to Table" }, { property: "og:description", content: "Create a fresh produce listing for your local marketplace." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary" }] }),
  component: ProductForm,
});

function ProductForm() {
  const navigate = useNavigate();
  const [error, setError] = useState("");
  const [busy, setBusy] = useState(false);
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setBusy(true); setError(""); const { data: userData } = await supabase.auth.getUser(); if (!userData.user) { await navigate({ to: "/auth" }); return; } const form = new FormData(event.currentTarget); const { error: insertError } = await supabase.from("produce_listings").insert({ farmer_id: userData.user.id, name: String(form.get("name") ?? ""), category: String(form.get("category") ?? "Vegetables"), description: String(form.get("description") ?? ""), price: Number(form.get("price") ?? 0), unit: String(form.get("unit") ?? "kg"), quantity: Number(form.get("quantity") ?? 0), location: String(form.get("location") ?? ""), harvest_date: String(form.get("harvest_date") ?? "") || null, image_url: String(form.get("image_url") ?? "") || null }); if (insertError) setError(insertError.message); else await navigate({ to: "/dashboard" }); setBusy(false); }
  return <FarmShell eyebrow="New listing"><PageIntro kicker="New harvest listing" title="Put a good crop on the table." body="Give buyers the details they need to make a confident request." /><main className="mx-auto max-w-3xl px-5 py-10 lg:px-8 lg:py-14"><Link to="/dashboard" className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground"><ArrowLeft className="size-4" /> Back to dashboard</Link><form onSubmit={save} className="mt-7 rounded-lg border border-border bg-card p-6 sm:p-8"><div className="grid gap-5 sm:grid-cols-2"><Field label="Produce name" name="name" placeholder="Heirloom tomatoes" required /><label className="grid gap-1.5 text-sm font-medium">Category<select name="category" defaultValue="Vegetables" className="rounded-md border border-input bg-background px-3 py-3 outline-none focus:border-field"><option>Vegetables</option><option>Fruit</option><option>Leafy greens</option><option>Herbs</option><option>Flowers</option></select></label><Field label="Price" name="price" type="number" placeholder="4.50" step="0.01" required /><Field label="Unit" name="unit" placeholder="kg" required /><Field label="Quantity available" name="quantity" type="number" placeholder="50" step="0.1" required /><Field label="Harvest date" name="harvest_date" type="date" /><Field label="Location" name="location" placeholder="Cedar Hollow Farm · 6 mi" /><Field label="Image URL" name="image_url" placeholder="Optional photo URL" /><label className="grid gap-1.5 text-sm font-medium sm:col-span-2">Description<textarea name="description" required className="min-h-32 resize-y rounded-md border border-input bg-background px-3 py-3 outline-none focus:border-field" placeholder="How was it grown? What makes this harvest worth bringing home?" /></label></div>{error && <p className="mt-5 text-sm text-destructive">{error}</p>}<div className="mt-7 flex flex-wrap justify-end gap-3"><Link to="/dashboard" className="rounded-md border border-border px-4 py-3 text-sm font-semibold hover:bg-secondary">Cancel</Link><button type="submit" disabled={busy} className="inline-flex items-center gap-2 rounded-md bg-field-deep px-5 py-3 text-sm font-semibold text-paper hover:bg-field disabled:opacity-60"><Save className="size-4" /> {busy ? "Publishing…" : "Publish listing"}</button></div></form></main></FarmShell>;
}
function Field({ label, name, placeholder, type = "text", step, required }: { label: string; name: string; placeholder?: string; type?: string; step?: string; required?: boolean }) { return <label className="grid gap-1.5 text-sm font-medium">{label}<input name={name} type={type} step={step} placeholder={placeholder} required={required} className="rounded-md border border-input bg-background px-3 py-3 outline-none focus:border-field" /></label>; }